"""Pygments lexer for Sail.

Keyword list mirrors ``kw_table`` in ``src/lib/lexer.mll``. Registering this
lexer (via the ``pygments.lexers`` entry point) makes every ``sail`` code
fence in a MkDocs site highlight, including pages generated by
``sail --mkdocs``.
"""

from __future__ import annotations

from pygments.lexer import RegexLexer, words
from pygments.token import (
    Comment,
    Keyword,
    Name,
    Number,
    Operator,
    Punctuation,
    String,
    Text,
)

KEYWORDS = (
    "and", "as", "assert", "backwards", "bitfield", "by", "cast", "catch",
    "clause", "config", "configuration", "constant", "constraint", "dec",
    "default", "do", "downto", "effect", "else", "end", "enum", "exit",
    "forall", "foreach", "forwards", "from", "function", "if", "impl",
    "impure", "in", "inc", "instantiation", "let", "mapping", "match",
    "monadic", "mutual", "newtype", "operator", "outcome", "overload",
    "private", "pure", "ref", "register", "repeat", "return", "scattered",
    "sizeof", "struct", "termination_measure", "then", "throw", "to", "try",
    "type", "undefined", "union", "until", "val", "var", "when", "while",
    "with",
)

KEYWORD_TYPES = ("Int", "Nat", "Order", "Bool", "Type")

BUILTIN_TYPES = (
    "atom", "bit", "bits", "bitvector", "bool", "implicit", "int", "list",
    "nat", "option", "range", "real", "result", "string", "unit", "vector",
)


class SailLexer(RegexLexer):
    """Lexer for the Sail ISA specification language."""

    name = "Sail"
    aliases = ["sail"]
    filenames = ["*.sail"]
    url = "https://github.com/rems-project/sail"

    tokens = {
        "root": [
            (r"//.*?$", Comment.Single),
            (r"/\*", Comment.Multiline, "comment"),
            (r"\$\[", Comment.Preproc, "attribute"),
            (r"\$\w+.*?$", Comment.Preproc),
            (r'"(\\.|[^"\\])*"', String.Double),
            (r"0x[0-9A-Fa-f_]+", Number.Hex),
            (r"0b[01_]+", Number.Bin),
            (r"\d+\.\d+", Number.Float),
            (r"\d+", Number.Integer),
            (r"\b(bitzero|bitone|true|false)\b", Keyword.Constant),
            (words(KEYWORDS, prefix=r"\b", suffix=r"\b"), Keyword),
            (words(KEYWORD_TYPES, prefix=r"\b", suffix=r"\b"), Keyword.Type),
            (words(BUILTIN_TYPES, prefix=r"\b", suffix=r"\b"), Name.Builtin),
            (r"'[a-zA-Z_]\w*", Name.Variable),
            (r"[a-zA-Z_?][a-zA-Z0-9_?#]*", Name),
            (r"[-+*/<>=!&|^%@:.]+", Operator),
            (r"[(){}\[\],;~]", Punctuation),
            (r"\s+", Text.Whitespace),
            (r".", Text),
        ],
        # Sail block comments nest
        "comment": [
            (r"[^/*]+", Comment.Multiline),
            (r"/\*", Comment.Multiline, "#push"),
            (r"\*/", Comment.Multiline, "#pop"),
            (r"[/*]", Comment.Multiline),
        ],
        "attribute": [
            (r"[^\[\]]+", Comment.Preproc),
            (r"\[", Comment.Preproc, "#push"),
            (r"\]", Comment.Preproc, "#pop"),
        ],
    }
