-- Generated by specialization_plan_checker.py.
-- Plan SHA-256: e0dac5914158e9785a5bc756691549c0cd2efa0bb6c397bfd42d14195a522add

def specializationPlanSchema : String := "1.0.0"
def representativeCloneIdentity : String := "clone:md5:260e01e1b8d5353669bdd3ba0ce4528e"
def representativeBoundPosition : String := "argument:0"
def representativeInferredUpper : Nat := 18446744073709551615
def representativeRepresentationUpper : Nat := 18446744073709551615
def specializationCloneCount : Nat := 2
def specializationObligationCount : Nat := 16

theorem schema_is_consumed : specializationPlanSchema = "1.0.0" := by rfl
theorem representative_identity_is_consumed :
    representativeCloneIdentity = "clone:md5:260e01e1b8d5353669bdd3ba0ce4528e" := by rfl
theorem representative_representation_adequacy :
    representativeInferredUpper ≤ representativeRepresentationUpper := by decide
theorem plan_contains_specialization : 0 < specializationCloneCount := by decide
theorem plan_contains_required_obligations :
    8 * specializationCloneCount ≤ specializationObligationCount := by decide
